[tool.flake8]
extend_exclude = [
    ".git",
    "venv",
    ".venv",
    "__pycache__",
    "dist",
]
# E203 - whitespace before ':' (ignore in the project folder)
# F401 - imported but unused (ignore in __init__.py)
# F403 - from ... import *; unable to detect undefined names (ignore in __init__.py)
extend_ignore = [
    "E203",
]
per_file_ignores = [
    "__init__.py: F401, F403",
]

[tool.isort]
skip_gitignore = true
multi_line_output = 3
include_trailing_comma = true

[tool.black]
line_length = 79
